apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aysu-dalogullari-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aysu-dalogullari-binding
  namespace: default
subjects:
- kind: User
  name: "aysu.dalogullari@usm.edu"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: aysu-dalogullari-role
  apiGroup: rbac.authorization.k8s.io
